# Ref: https://github.com/jekyll/minima/blob/master/_config.yml
title: notebooks
author: Sangram Keshari Sahu

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: sangram_ksahu
    github:  sk-sahu
    rss: rss

# Build settings
theme: minima
